"""Create tables User and Application

Revision ID: 46d6d90cefff
Revises: 
Create Date: 2025-02-20 15:44:06.353529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46d6d90cefff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('application',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('reg_day', sa.Integer(), nullable=False),
    sa.Column('reg_month', sa.Integer(), nullable=False),
    sa.Column('reg_year', sa.Integer(), nullable=False),
    sa.Column('outgoing_id', sa.String(length=255), nullable=False),
    sa.Column('outgoing_day', sa.Integer(), nullable=False),
    sa.Column('outgoing_month', sa.Integer(), nullable=False),
    sa.Column('outgoing_year', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('purchase_subject', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('economist_info', sa.Text(), nullable=True),
    sa.Column('purchase_info', sa.Text(), nullable=True),
    sa.Column('exec_docs_info', sa.Text(), nullable=True),
    sa.Column('lawyer_info', sa.Text(), nullable=True),
    sa.Column('accountant_info', sa.Text(), nullable=True),
    sa.Column('economist_status', sa.String(length=50), nullable=True),
    sa.Column('purchase_status', sa.String(length=50), nullable=True),
    sa.Column('exec_docs_status', sa.String(length=50), nullable=True),
    sa.Column('lawyer_status', sa.String(length=50), nullable=True),
    sa.Column('accountant_status', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('users')
    op.drop_table('applications')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('reg_day', sa.INTEGER(), nullable=False),
    sa.Column('reg_month', sa.INTEGER(), nullable=False),
    sa.Column('reg_year', sa.INTEGER(), nullable=False),
    sa.Column('outgoing_id', sa.TEXT(), nullable=False),
    sa.Column('outgoing_day', sa.INTEGER(), nullable=False),
    sa.Column('outgoing_month', sa.INTEGER(), nullable=False),
    sa.Column('outgoing_year', sa.INTEGER(), nullable=False),
    sa.Column('company_name', sa.TEXT(), nullable=False),
    sa.Column('purchase_subject', sa.TEXT(), nullable=False),
    sa.Column('amount', sa.REAL(), nullable=False),
    sa.Column('economist_info', sa.TEXT(), server_default=sa.text("('')"), nullable=True),
    sa.Column('purchase_info', sa.TEXT(), server_default=sa.text("('')"), nullable=True),
    sa.Column('exec_docs_info', sa.TEXT(), server_default=sa.text("('')"), nullable=True),
    sa.Column('lawyer_info', sa.TEXT(), server_default=sa.text("('')"), nullable=True),
    sa.Column('accountant_info', sa.TEXT(), server_default=sa.text("('')"), nullable=True),
    sa.Column('economist_status', sa.TEXT(), server_default=sa.text("'empty'"), nullable=True),
    sa.Column('purchase_status', sa.TEXT(), server_default=sa.text("'empty'"), nullable=True),
    sa.Column('exec_docs_status', sa.TEXT(), server_default=sa.text("'empty'"), nullable=True),
    sa.Column('lawyer_status', sa.TEXT(), server_default=sa.text("'empty'"), nullable=True),
    sa.Column('accountant_status', sa.TEXT(), server_default=sa.text("'empty'"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('username', sa.TEXT(), nullable=False),
    sa.Column('password', sa.TEXT(), nullable=False),
    sa.Column('role', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('application')
    op.drop_table('user')
    # ### end Alembic commands ###
